name: iba_cocktail_list_flutter
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  -  assets/Alexander.jpg
  -  assets/Americano.jpg
  -  assets/Angel Face.jpg
  -  assets/Aviation.jpg
  -  assets/B52.jpg
  -  assets/Bacardi.jpg
  -  assets/Barracuda.jpg
  -  assets/Bellini.jpg
  -  assets/Black Russian.jpg
  -  assets/Bloody Mary.jpg
  -  assets/Bramble.jpg
  -  assets/Caipirinha.jpg
  -  assets/Casino.jpg
  -  assets/Champagne Cocktail.jpg
  -  assets/Club.jpg
  -  assets/Cosmopolitan.jpg
  -  assets/Cuba Libre.jpg
  -  assets/Daiquiri.jpg
  -  assets/Dark 'n' Stormy.jpg
  -  assets/Derby.jpg
  -  assets/Dirty Martini.jpg
  -  assets/Dry Martini.jpg
  -  assets/Espresso Martini.jpg
  -  assets/French Connection.jpg
  -  assets/French Martini.jpg
  -  assets/French 75.jpg
  -  assets/Gin Fizz.jpg
  -  assets/Godfather.jpg
  -  assets/Godmother.jpg
  -  assets/Golden Dream.jpg
  -  assets/Grasshopper.jpg
  -  assets/Harvey Wallbanger.jpg
  -  assets/Hemingway Special.jpg
  -  assets/Horse's Neck.jpg
  -  assets/Irish Coffee.jpg
  -  assets/John Collins.jpg
  -  assets/Kamikaze.jpg
  -  assets/Kir.jpg
  -  assets/Lemon Drop.jpg
  -  assets/Long Island Iced Tea.jpg
  -  assets/Mai-Tai.jpg
  -  assets/Manhattan.jpg
  -  assets/Margarita.jpg
  -  assets/Mary Pickford.jpg
  -  assets/Mimosa.jpg
  -  assets/Mint Julep.jpg
  -  assets/Mojito.jpg
  -  assets/Monkey Gland.jpg
  -  assets/Moscow Mule.jpg
  -  assets/Negroni.jpg
  -  assets/Old Fashioned.jpg
  -  assets/Paradise.jpg
  -  assets/pic1.jpg
  -  assets/Pina Colada.jpg
  -  assets/Pisco Sour.jpg
  -  assets/Planter's Punch.jpg
  -  assets/Porto Flip.jpg
  -  assets/pritz Veneziano.jpg
  -  assets/Ramos Gin Fizz.jpg
  -  assets/Rose.jpg
  -  assets/Russian Spring Punch.jpg
  -  assets/Rusty Nail.jpg
  -  assets/Sazerac.jpg
  -  assets/Screwdriver.jpg
  -  assets/Sea Breeze.jpg
  -  assets/Sex On The Beach.jpg
  -  assets/Sidecar.jpg
  -  assets/Singapore Sling.jpg
  -  assets/Stinger.jpg
  -  assets/Tequila Sunrise.jpg
  -  assets/The Sheets.jpg
  -  assets/Tommy's Margarita.jpg
  -  assets/Tuxedo.jpg
  -  assets/Vampiro.jpg
  -  assets/Vesper.jpg
  -  assets/Whiskey Sour.jpg
  -  assets/White Lady.jpg
  -  assets/Yellow Bird.jpg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
